/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0c1322',
        'surface-dim': '#0c1322',
        'surface-bright': '#323949',
        'surface-container-lowest': '#070e1d',
        'surface-container-low': '#141b2b',
        'surface-container': '#191f2f',
        'surface-container-high': '#232a3a',
        'surface-container-highest': '#2e3545',
        'on-surface': '#dce2f7',
        'on-surface-variant': '#bac9cc',
        'inverse-surface': '#dce2f7',
        'inverse-on-surface': '#293040',
        outline: '#849396',
        'outline-variant': '#3b494c',
        'surface-tint': '#00daf3',
        primary: '#c3f5ff',
        'on-primary': '#00363d',
        'primary-container': '#00e5ff',
        'on-primary-container': '#00626e',
        'inverse-primary': '#006875',
        secondary: '#ffd795',
        'on-secondary': '#422c00',
        'secondary-container': '#fbb400',
        'on-secondary-container': '#694900',
        tertiary: '#ffe7ed',
        'on-tertiary': '#640039',
        'tertiary-container': '#ffbfd6',
        'on-tertiary-container': '#ac0768',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#9cf0ff',
        'primary-fixed-dim': '#00daf3',
        'on-primary-fixed': '#001f24',
        'on-primary-fixed-variant': '#004f58',
        'secondary-fixed': '#ffdea9',
        'secondary-fixed-dim': '#ffba27',
        'on-secondary-fixed': '#271900',
        'on-secondary-fixed-variant': '#5e4100',
        'tertiary-fixed': '#ffd9e4',
        'tertiary-fixed-dim': '#ffb0cd',
        'on-tertiary-fixed': '#3e0022',
        'on-tertiary-fixed-variant': '#8c0053',
        background: '#0c1322',
        'on-background': '#dce2f7',
        'surface-variant': '#2e3545',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xxs': '2px',
        'space-xs': '4px',
        'space-sm': '8px',
        'space-md': '12px',
        'space-lg': '16px',
        'space-xl': '24px',
        'space-xxl': '32px',
        'gutter-dense': '4px',
        'gutter-panel': '8px',
        'gutter-screen': '12px',
      },
      fontFamily: {
        'display-hud': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'mono-data-sm': ['JetBrains Mono', 'monospace'],
        'mono-data-md': ['JetBrains Mono', 'monospace'],
        'mono-data-lg': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-hud': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '700' }],
        'mono-data-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '400' }],
        'mono-data-md': ['13px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '500' }],
        'mono-data-lg': ['16px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-lg-mobile': ['18px', { lineHeight: '24px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
